# Generated by Django 4.2 on 2023-04-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_hygience_complaint_delete_complaints"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hygience_Complaint",
            new_name="Hygiene_Complaint",
        ),
    ]
