# Generated by Django 4.2 on 2023-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_hygience_complaint_hygiene_complaint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finance_Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("complaint", models.CharField(max_length=2000)),
            ],
        ),
    ]
